
@host = https://localhost:8000
@accessToken  = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmhhZGlwMTIwM0BnbWFpbC5jb20iLCJmdWxsTmFtZSI6InN1YmFoZGlwIiwiaWQiOiI2MjgzZGMwNDAwNjU1NTYxYmZhYjZhZGYiLCJpYXQiOjE2NTMxNTU2ODAsImV4cCI6MTY1MzE1NTY4MH0.3gbdGtHuFHXpEQIX1sxpugLeKI5Tjedc_Lz6c9DA-hA


### -- Login ---
POST {{host}}/v1/auth/login 
content-type: application/json

{
    "email": "subhadip1203@gmail.com",
    "password": "12345"
}

### -- registration --
POST {{host}}/v1/auth/register 
content-type: application/json

{
    "email": "subhadip1203@gmail.com",
    "name": "subahdip",
    "password": "12345"
}


### -- auth test --
GET {{host}}/v1/auth/
content-type: application/json
Authorization: {{accessToken}}









