
@host = https://localhost:8000
@accessToken  = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmhhZGlwMTIwM0BnbWFpbC5jb20iLCJmdWxsTmFtZSI6InN1YmFoZGlwIiwiaWQiOiI2MjgzZGMwNDAwNjU1NTYxYmZhYjZhZGYiLCJsb2dpblBhc3N3b3JkIjoiJDJiJDEwJFV3LkdiYzR0WVgxaDBMWjFRcWFrV09VNWRIbWg1eGJER2tRWnFEazVYMUcxMlg0SHJram91IiwiaWF0IjoxNjUzMTUzMTA3LCJleHAiOjE2NTMxNTMxMTB9.-eFLiQ6KwOYHk-UH4hswM2_aUrf5x6lbnU6FcNN6mTs



### -- Login ---
POST {{host}}/v1/auth/login 
content-type: application/json

{
    "email": "subhadip1203@gmail.com",
    "password": "12345"
}

### -- registration --
POST {{host}}/v1/auth/register 
content-type: application/json

{
    "email": "subhadip1203@gmail.com",
    "name": "subahdip",
    "password": "12345"
}


### -- auth test --
GET {{host}}
content-type: application/json
Authorization: {{accessToken}}









